### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PhatPhantom** [ziman/scan-eSCL#3]
python3 scan.py -o pythontest.jpg -p 80 -c RGB24 192.168.0.11
Traceback (most recent call last):
  File "scan.py", line 69, in <module>
    main(ap.parse_args())
  File "scan.py", line 40, in main
    scanner_url = 'http://' + args.scanner_ip + ':' + str(port)
NameError: name 'port' is not defined

**Comment by ziman** [comment]
Thank you!

Fixed in `master`.
